### ISSUE TITLE
plugin pages should include an example configuration in yml format

### ISSUE THREAD

**Issue by mertbakir** [meltano/hub#1369]
Hello, I think all plugin pages (e.g. tap-postgres, tap-jira, airflow etc) should contain a configuration example to copy paste. More detailed version would be better but it should at least show the base minumum required fields. For example:

```yaml
plugins:
  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
````

**Reason 1:**
I don't like to use ```meltano add ...``` command because it reformats the yml file, I want to add the configuration manually then use ```meltano install```. 

**Reason 2:**
Other than that it's would still be beneficial for clear documentation. Configuration of some taps/targets are probably hard to understand for new-comers, at least it was for me, without many trial/error or asking in the community.
