### ISSUE TITLE
Publish Solarvista Live (tap-solarvista) on Meltano Hub

### ISSUE THREAD

**Issue by MeltyBot** [meltano/hub#141]
Migrated from GitLab: https://gitlab.com/meltano/hub/-/issues/144

Originally created by @aphethean on 2021-10-18 11:56:30

---

Through our partnership with Solarvista Matatika have built and open sourced a Singer.io tap for Solarvista Live.

We will shortly create the pull request for publishing the tap.

All Singer definitions are stored in `/_data/taps/` or `/_data/targets` and logo images are in `/assets/logos/<taps or targets>`. The minimial steps for adding a tap or target are the following:

## Checklist

- [x] Fork the MeltanoHub and create a branch, you can name the branch anything you like.
- [x] Add a yaml configuration file in the appropriate folder (`/_data/taps/` or `/_data/targets`). The name of the file should match the name of the tap. If there is already one, add a descriptor to the name such as `-search`.
- [x] Add a png logo image in `/assets/logos/<taps or targets>`. The image name must match the YAML file name and should be a reasonable size (ideally less than 100K).
- [x] Create a Merge Request to `main` from the new branch in your fork and select the template "Add a New Singer Connector".
- [x] Tag `@tayloramurphy` or `@pnadolny13` to flag it for review. Or post to the hub channel on Meltano slack.

## Detailed Steps (GitLab Web Editor)

- Click Web IDE on the [MeltanoHub repo](https://gitlab.com/meltano/hub)
- You'll be prompted to create a fork since you dont have access to edit directly. This automatically create a fork in your project and land you in the web editor.
- Add your yaml config file in `/_data/taps/` by clicking "New File". You can use the sample below to get started.
- Upload your png image in `/assets/logos/<taps or targets>` by clicking "Upload File".
- Click the commit, write a write a message, then commit again (keep "Create new branch" and "Start a new merge request selected")
- Choose the "Add new Singer Connector" template in the merge request
- Tag `@tayloramurphy` or `@pnadolny13`

## Sample yaml file

```yaml
description: |-
  Solarvista Live is a Field Service Management platform to manage, plan, and mobilise your engineers.  The Matatika
  Solarvista Live import will extract Solarvista data into your Matatika data store, giving you instant insights into
  revenue, projects, work items, and engineer performance.
domain:
  description: Field Service Management
  name: Solarvista Live API
  type: api
  url: https://www.matatika.com/docs/datasources/tap-solarvista/
label: Solarvista Live
name: solarvista
singer_name: tap-solarvista
type: tap
variants: matatika
- default: true
  maintenance_status: "Active"
  meltano_sdk: false
  name: Matatika
  repo: https://github.com/Matatika/tap-solarvista
  pip_url: git+https://github.com/Matatika/tap-solarvista.git
  capabilities:
    - state
  settings:
    - name: datasources
      env_aliases:
        - TAP_SOLARVISTA_DATASOURCES
      label: Datasources
    - name: account
      env_aliases:
        - TAP_SOLARVISTA_ACCOUNT
      label: Account
    - name: clientId
      env_aliases:
        - TAP_SOLARVISTA_CLIENTID
      label: Client ID
    - name: code
      env_aliases:
        - TAP_SOLARVISTA_CODE
      label: Code
    - name: start_date
      env_aliases:
        - TAP_SOLARVISTA_START_DATE
      label: Start Date
      kind: date_iso8601
```
