### ISSUE TITLE
Publish 'tap-thunderboard' created during Taptoberfest

### ISSUE THREAD

**Issue by MeltyBot** [meltano/hub#149]
Migrated from GitLab: https://gitlab.com/meltano/hub/-/issues/152

Originally created by @aphethean on 2021-10-22 08:48:58

---

Created a new tap for Silicon Labs Thunderboards environmental data - temperature, uv, ambient light.

All Singer definitions are stored in `/_data/taps/` or `/_data/targets` and logo images are in `/assets/logos/<taps or targets>`. The minimial steps for adding a tap or target are the following:

## Checklist

- [x] Fork the MeltanoHub and create a branch, you can name the branch anything you like.
- [x] Add a yaml configuration file in the appropriate folder (`/_data/taps/` or `/_data/targets`). The name of the file should match the name of the tap. If there is already one, add a descriptor to the name such as `-search`.
- [x] Add a png logo image in `/assets/logos/<taps or targets>`. The image name must match the YAML file name and should be a reasonable size (ideally less than 100K).
- [x] Create a Merge Request to `main` from the new branch in your fork and select the template "Add a New Singer Connector".
- [x] Tag `@tayloramurphy` or `@pnadolny13` to flag it for review. Or post to the hub channel on Meltano slack.

## Detailed Steps (GitLab Web Editor)

- Click Web IDE on the [MeltanoHub repo](https://gitlab.com/meltano/hub)
- You'll be prompted to create a fork since you dont have access to edit directly. This automatically create a fork in your project and land you in the web editor.
- Add your yaml config file in `/_data/taps/` by clicking "New File". You can use the sample below to get started.
- Upload your png image in `/assets/logos/<taps or targets>` by clicking "Upload File".
- Click the commit, write a write a message, then commit again (keep "Create new branch" and "Start a new merge request selected")
- Choose the "Add new Singer Connector" template in the merge request
- Tag `@tayloramurphy` or `@pnadolny13`

## Sample yaml file

```yaml
description: Silicon Labs Thunderboard's collect environmental data - temperature, uv, ambient light - from a physical device.
domain:
  description: Sensors
  name: Silicon Labs Thunderboard
  type: file
  url: https://www.silabs.com/community/projects.entry.html/2017/03/08/thunderboard_sensew-Scqr
label: Thunderboard
name: thunderboard
singer_name: tap-thunderboard
type: tap
variants:
- default: true
  maintenance_status: Unknown
  meltano_sdk: true
  name: Matatika
  pip_url: git+https://github.com/Matatika/tap-thunderboard
  repo: https://github.com/Matatika/tap-thunderboard
  capabilities:
    - catalog
    - discover
  settings:
    - name: mode
      description: dump | file - 'dump' mode scans for devices and dumps measurements continuously.
    - name: dataDirectory
      description: The local directory where thunderboard data can be found
    - name: filename
      description: The name of the file in the data directory to be processed
    - name: cleanup
      description: Optional cleanup the file contents after processing (Default: True)
    - name: deviceId
      description: An optional device id to limit output from discovered thunderboards
```
