### ISSUE TITLE
Re-think domain and descriptions for Singer connectors

### ISSUE THREAD

**Issue by MeltyBot** [meltano/hub#150]
Migrated from GitLab: https://gitlab.com/meltano/hub/-/issues/153

Originally created by @tayloramurphy on 2021-10-22 18:11:34

---

Currently we have this sort of structure for the definitions of taps and targets:

```yaml
description: Cloud-based Warehouse Management System (WMS)
domain:
  description: Cloud-based Warehouse Management System (WMS)
  name: 3PLCentral API
  type: api
  url: https://www.3plcentral.com
```

My original intent with `domain` was to be able to bucket similar taps based on some sort of hierarchy. Facebook is a good example where we have 4 different taps that would be nice to see under a general "Facebook" page with links to the specific ads, pages, posts, and reviews taps. 

As it turns out, neither of the `description` keys are used anywhere on MeltanoHub currently. The `name` under the domain is used in the description sentence of a connector as follows:

`The <tap_name> Singer Target pulls data from the <domain.name> that can then be sent to a destination using a Singer Target.`

So it's not really even a name, technically. 

My general proposal (which I'm 100% open to changing) is to rename `domain` to something else and then use something else to bucket similar connectors. We should also drop unnecessary and duplicate descriptions (I think my original thought is that people could better understand what a tool was but honestly there's google for that).

```yaml
# Old
description: Advertising Platform
domain:
  description: Advertising Platform
  name: Facebook Ads API
  type: api
  url: https://developers.facebook.com/docs/marketing-apis
label: Facebook Ads
name: facebook
singer_name: tap-facebook
type: tap
variants:
```

And maybe we could add a domains.yml file as a separate thing (though it's not super necessary right now).

```yaml
# facebook.yml
meta:
  title: Facebook Ads API
  domain: facebook
  type: api
  url: https://developers.facebook.com/docs/marketing-apis
label: Facebook Ads
name: facebook #unrelated to the domain - this was just the first facebook tap and it happens to be for Ads.
singer_name: tap-facebook
type: tap
variants:
...

# domains.yml
facebook:
  label: Facebook
  url: https://facebook.com
  description: <optional>
```

@pnadolny13 @aaronsteers what do you think about this?
