### ISSUE TITLE
Example meltano.yml generated for all taps/targets

### ISSUE THREAD

**Issue by MeltyBot** [meltano/hub#158]
Migrated from GitLab: https://gitlab.com/meltano/hub/-/issues/161

Originally created by @vischousous on 2021-11-09 20:06:00

---

Guessing this isn't a new idea, but I didn't see it listed in the issues list. 

Looking at https://hub.meltano.com/taps/clickup and thought why do people need to create their own custom extractor meltano configuration.

On top of the data listed there, we could also generate a meltano.yml file

```yml
plugins:
  extractors:
  - name: tap-clickup
    namespace: tap_clickup
    pip_url: tap-clickup
    capabilities:
    - state
    - catalog
    - discover
    settings:
    select:
    - '*.*'
    config:
      start_date: 'todo'
      api_token: 'todo'
```

I know that's what the `discovery.yml` piece is for, but it seems like we could get pretty close here?
