### ISSUE TITLE
Add Plugin: tap-planetscale

### ISSUE THREAD

**Issue by visch** [meltano/hub#1684]
### What is the plugin type?

extractor

### Repository URL

https://github.com/planetscale/singer-tap/

### Description

PlanetScale is the world’s most advanced MySQL platform

### Domain URL

https://planetscale.com/docs

### Logo Image

![planetscale](https://github.com/meltano/hub/assets/8680264/2b569a72-ab6f-4b07-b089-09348505876d)

### Any other notes?

This tap is written in Go.

Note that with some settings set automatically MeltanoLabs tap-mysql tap can support this as well (After https://github.com/MeltanoLabs/tap-mysql/pull/45 is merged)

**Comment by edgarrmondragon** [comment]
The problem with having this in the Hub would be that `meltano add` wouldn't be sufficient to set up the tap: users would still need to download or build the right binary, and then point `executable` to it. I don't know if we have another non-Python tap in the Hub.

**Comment by tayloramurphy** [comment]
@edgarrmondragon I have a memory of another non-python tap, but I don't think we added it to the Hub. Maybe @pnadolny13 remembers? It may have been this mysql one to be honest.

**Comment by edgarrmondragon** [comment]
There's https://github.com/MeltanoLabs/target-jsonl-blob which is also Golang-based, which we never added to the Hub.

**Comment by visch** [comment]
We could probably do something better than this but here's a "working" example. Note that their tap doesn't follow the singer spec so I don't think we can add this anyway :/  See https://github.com/planetscale/singer-tap/issues/51 maybe they'll adjust it though!


```
  extractors:
  - name: tap-planetscale
    namespace: tap_planetscale
    pip_url: cowsay
    executable: /home/visch/git/tap-mysql/ps-singer-tap
    capabilities:
    - state
    - catalog
    - discover
    - about
    - stream-maps
    settings:
    - name: host
    - name: username
    - name: database
    - name: password
      sensitive: true
    config:
      host: aws.connect.psdb.cloud
      username: 0fiqne6txvcqtjbdywan
      database: tap-mysql
    select:
    - "*.*"
```
