### ISSUE TITLE
Singer Metadata API - Proposal

### ISSUE THREAD

**Issue by MeltyBot** [meltano/hub#177]
Migrated from GitLab: https://gitlab.com/meltano/hub/-/issues/180

Originally created by @pnadolny13 on 2021-12-13 21:40:52

---

The gap the singer community has right now is that theres no reliable way for an application to access tap/target metadata. Its much easier for SDK based connectors but we need a short term solution since the majority are not SDK based and its not worth it to come up with standard settings and get them installed in every legacy tap/target.

We compiled a ton of useful info for the hub docs but its not useful for applications yet, although we're very close. We expose the tap/target json endpoints but without versioning individual taps, its not very useful for building applications on (including Meltano). The hub has current state of settings which is good for docs and new installers but not for stability of existing pipelines.

I propose that we create a singer metadata API. Once this exists Meltano will have a much easier time interacting with community/legacy connectors.

A solution I've been thinking of is:

* we add a new `version` key to all the hub yamls
* pypi installable packages or git repos that have release tags get pinned with those
* for raw git urls we pin a commit hash and we assign it a 3rd party semantic version. For these we can manage bumping the commit hash and determining if its a small/med/large version via a hub MR. This unlocks Meltano features to know when a tap/target has a breaking change.
* every change to these hub yamls is sent to the singer metadata service API (probably in CI)

Singer Metadata API:

* receives changes from the hub of yaml files which are snapshotted and stored in S3 or dyanmo by plugin/variant/version
* a GET endpoint which returns the settings given a plugin/variant/version (and we can return defaults too)
* eventually we can incorporate more automation here to keep things up to date

This would also give the Singer community the missing piece that it needs for applications to easily be built on top of it (i.e. hotglue, Matatika dont need to manage metadata anymore).

Open Questions and thoughts:
- we need to decide what happens when a metadata definition is found to be incorrect in the hub but the package version is the same. Is it alright to overwrite the existing metadata definition in the API?
- git url versioning with commit hashes we need to decided on how the yaml definitions track this. Maybe like the below example or just include the hash in the pip_url.
```yaml
label: Sample
name: sample
singer_name: tap-sample
type: tap
variants:
- default: true
  name: foo_user
  pip_url: tap-sample
  version: 1.0.1
  ...
- default: false
  name: bar_user
  pip_url: git+https://github.com/bar_user/tap-sample.git
  git_hash: 9eabf5b536662000f79978c4d1b6e4eff5c8d785
  3P_version: 0.0.1
```
- Should we track the setup.py version? Many times its not reliable because people commit right to the main branch without bumping versions.
- for git url versioning we need to append a namespace or something in the case that a package was unversioned then ended up being versioned, so we dont have future conflicts.
