### ISSUE TITLE
dbt plugins are all stuck to version 1.3 which means you're stuck below Python 3.11

### ISSUE THREAD

**Issue by visch** [meltano/hub#1821]
https://github.com/search?q=repo%3Ameltano%2Fhub%201.3.0&type=code 

Updating locally to the below works!

```
  transformers:
  - name: dbt-postgres
    variant: dbt-labs
    pip_url: dbt-core~=1.8.0 dbt-postgres~=1.8.0
```
