### ISSUE TITLE
toggl - updated repo

### ISSUE THREAD

**Issue by MeltyBot** [meltano/hub#230]
Migrated from GitLab: https://gitlab.com/meltano/hub/-/issues/234

Originally created by @vischousous on 2022-04-12 20:38:18

---

https://github.com/singer-io/tap-toggl looks to be more up to date than the current recommended toggl tap

```
  extractors:
  - name: tap-toggl
    namespace: tap_toggl
    pip_url: tap-toggl
    executable: tap-toggl
    capabilities:
    - catalog
    - discover
    - state
    settings:
    - name: api_token
      kind: password
    - name: detailed_report_trailing_days
      kind: integer
    - name: start_date
      kind: string
    - name: user_agent
      kind: string
```

Verified that everything works here
