### ISSUE TITLE
Standardize setting types including sensitive and other properties

### ISSUE THREAD

**Issue by MeltyBot** [meltano/hub#24]
Migrated from GitLab: https://gitlab.com/meltano/hub/-/issues/25

Originally created by @tayloramurphy on 2021-05-05 16:24:53

---

Specifically around `kind: password`, this should be refactored into something like:

```yaml
- name: pg_password
  kind: string
  sensitive: true
```

**Comment by MeltyBot** [comment]
[View 34 previous comments from the original issue on GitLab](https://gitlab.com/meltano/hub/-/issues/25)

**Comment by aaronsteers** [comment]
I heard back from the JSON Schema Slack group:

https://json-schema.slack.com/archives/C5CF75URH/p1655689487229799?thread_ts=1655539008.232609&cid=C5CF75URH

From [ether](https://json-schema.slack.com/team/U010M301BSL) in Slack:
> The way to do that in JSON Schema is with `"writeOnly": true`
> https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.9.4

T

**Comment by aphethean1** [comment]
My 2p, I'm in favour of 'sensitive' as the property name.

Another concrete use case we have.  Refresh token is a hidden setting on some of our taps.  This setting is not shown to the user, but is sensitive and should be stored encrypted.

**Comment by tayloramurphy** [comment]
Notes from chat with AJ:

* Allow both JSON schema and kind
* JSON schema would override

Possibly either one of these but perhaps not both

```yaml
- name: pg_password
   kind: string
   sensitive: true

#  add JSONSchema option
- name: pg_password
   kind: string # this is ignored if schema is provided
   schema: 
     type: string
     writeOnly: true
```

`meltano config list --format=jsonschema` have it output JSONschema
