### ISSUE TITLE
Remove --variant option from install instructions for non-discoverable plugins

### ISSUE THREAD

**Issue by MeltyBot** [meltano/hub#242]
Migrated from GitLab: https://gitlab.com/meltano/hub/-/issues/247

Originally created by @pnadolny13 on 2022-05-02 15:07:26

---

The variant specific pages tells users to add the tap using `--variant` which I dont think is relevant for non-Meltano optimized taps/targets. It still ends up asking for a pip url that defaults to the pypi name. So the outcome when I tested following https://hub.meltano.com/taps/s3-csv--fishtown-analytics was:

1. `meltano add --custom extractor tap-s3-csv --variant fishtown-analytics`
1. accept all CLI prompt defaults
1. the singer variant is installed because its installed from pypi but the variant is set to `fishtown-analytics` in my meltano.yml.

```yaml
  extractors:
  - name: tap-s3-csv
    namespace: tap_s3_csv
    variant: fishtown-analytics
    pip_url: tap-s3-csv
    executable: tap-s3-csv
```
