### ISSUE TITLE
Add a New Meltano Extractor for Solarvista Live - [closed]

### ISSUE THREAD

**Issue by MeltyBot** [meltano/hub#388]
_Merges issues/144-meltanoextractor -> main_

Migrated from GitLab: https://gitlab.com/meltano/hub/-/merge_requests/138

---

In our platform we can accept full or partial discovery.yml files.  The idea is that we will create many transforms, and analyze bundles that can be installed seamlessly through our app by less technical users, with a full Meltano project created and maintained at the backend.

This pull request includes all that we need to automatically publish the extractor, the transforms, and the BI datasets.

If its not already in our platform, we would normally expect a user to upload a discovery.yml subset as follows:

```
version: 19
extractors:
  - name: tap-solarvista
    label: Solarvista Live
    description: |-
    
      ![Solarvista Live](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAMAAABrrFhUAAAAM1BMVEVHcEx6NGW4Q0H2Uh5hRJBfLnSbPFJKKYD/VBn////nTifs6fLSSTOGcKugjry8sNHSyuC5G9LfAAAAAXRSTlMAQObYZgAAC2RJREFUeNrsnduCoyAMQDdAwh35/6/dB0DR2pm2WhWHPM22sx055AqB/vvXpUuXLl26dOnSpUuXLl26dOnSpUuXLl26dOnSpUuXPy9C3kJEB9ABdAAdQAfQAXQAHUAH0AFcAwAiEDHGmGOMEQHiHwKAxJzhai7cOAL8AwCAjFoTrpRS/GsQLgIAn4y+FsO+weASAIBx9ZJwBjcEAO7F4SullHKE9wKA7J3hJzXAGwGgd4e/tyWcCwCd+ky4gzsA+Gj6dzaEMwGwDePfDcF5AJCprWKoZQBO7SDbXcFZAHCX8SvFqVEATO0lrEkA+41/K4FzAJDaU6g5AMB3BcCxMQBo1L7CGgPAdh7/JhU4AcDOBrDRC5wAwO0+fuVaAgD7j3+LDRwOAL+gAEo1BOAbCqAUtAPA/XEA+JXx83YAsO8AaMcHmK8AMM2EwVeTIG4cY4ytbBXunQsfDOC1MrDa/EAEZr4YBY8G8EoMeFzp+43BhkTwaAAvuAC3Np0I7isx4GgA+OH4f95C3LQkdCwA2hTQnmjBFgO4HoCfC1swb6jMFQGwzRnNw27a1u2hYwH8GgR+V2ecuYLte0PHAjDbLGARFPkezRIXA/BiQEMg2qlr6lAAaL5X1nYA9wBA9wbwuw9gf10DjreBi2nA1ryu+UToeCO4HICjCVysFjjeCq5WDe7V/HVRAK9uCxm4KQB8eWfcwS0BvLMtcJAhHAzgrY0hhvcD8F57GLsfAHyvPYZuB+DN3XFzPwBvtkjC7QC8aQMsr4DB145OHt4h8l6DgJMSyfFdD8mcDOA9FWD1XshXEBzfJvdeKkDfzpCPB/CWCiw2RL9A4IRO0S298u4OADa1StINAGzqlnZSSglE0DKATUaASYP4XutG5xyZ2dAtSGVt3TR9cvRzN0Bu31rxJACfO8LpvC3HhgF8fm6I7VwpnXZ09lMdoF3aIy8A4EMCBm9iAvLD4+M0RRAGzJjNXTJn3h+A7+cDHEbvYbI73FgfnHuFBrzvCjkjx5XijO3SKXv2JSqvXKC0cn8IAFb5tGsYgJQSiLE3vYGBeTIJTQN4d8coEzA7lYgXAUCfR8MGD0/vUR6xm2nAojz6/agQd/fyAbLuAzck8ddOAnebKFBlhoYrxQ3hK07B3SMPWDIYd4BeOFlwh0xwg1PkKIEZvrll/qoA6IXFwXITpdlyu95VAVRx3jzTgGpxiG4HYFIBR09SIbdLM8l1b5ZmpW0SfokC2whc+GptYMY4eFYouJ2Oj7Zwt/iaDRiz07ZhCwDWVpDZXkfIm7hd/nEzcc0z0n0BPBiBW1tQZTcGsDgx61D+NQC1H+C0nirfGwBxZZzhvGwEsL/lA6R0SjEkZ1zO+2GvpspmNEAp5qojNY+h8cO22ma+ZKX6DgIOK4Hh03qoGQD1MrBB+dBj8em6WDMA2NLhz43g44aZZsIgX9o71rnB5y1TrQCApcefDZ/IufZ8wFtfobTweUSll5gRYXq3oTwAEVAC5yAlfgigXCOSOJrP3cAZAMhwzomUIjL8xdNxSxMoBgBkOMO2AGTrdS6var2Uwy99fgFAfOwddI2YwPjskH96bTGLzdP+0idD6YCh+zgQHg+Apian16sYnKmAy25PcYL0AQjQTBic1rtHAL/0fgMzxrCpmcYQEZBJ6S9TyiEzrSyLA8GkAVVyw15YDGEsf/GcSfjSpCOghA09AoffH8DHDAayXZufPThVZ4mBCKDqFkdyxjiADT0Cx1+hUc5BOQlAhhsGfAKAD+cD66UgkHUR5MZmU2rGBJxSyiXzZUiKEyJKScbkb9ZkXHGSYBxKCcwxmGdAbF4UTJtjzWyOouHGcUxtAE4ph44bkBId54ZStsPBKMWS5XOahT83z4imFYJWrtcHQiJgzJi8rsmcUopjVnNi45EIyhM93wI1cwCuuZulGUeTh8mklJBToVLZ8AwAGY2aT0sNqLrFXXPX6yOiyVHAoMQymvEUDPExILBF2ZdTJ6JJJardoYbuFkfE0uJjUhpTqTmAK2ekaXlGSuUIaqYwCM35gCSmpIEGJTLnSj4wziOOuqEM1nmAU0opSrfruqpfmLfVIgNcKQ7I87zBmNukZA5TWwBwpRQHxDETpJQCsOngZFYd3lqnKBKhlDBt8ThwXHE25QqKo0RiBE4pA6kWAEw7ogDMlLYoJGcMa7pPMNkxm1JAqI/ImjLBiMxwwxg3lCsCJqVkxmy+V/YsAKV8paUTY9U+z/RzVnZXuQSW3m70+waR5yd/AEAVADN1xC1XQpTiyU+axgGkKAdJ4dloE+ldM6Y5ZrmGULKGVgEUFygluLIuytJgiI8bHaMJjOmfqfIi5vY4QXyBjZHixrDsfFPx65M2mJXeIAKzw+2L194ZAseVqRtCCOrdoc9XAq8BAJ7tCUzjwhwec0LsqvUQ0/43T9MTA6aV3DblAYjjWUu+0yUa5x6dxWfrRrRaRpEzLpcC5hZfvv5062x9eHnBaNc7VK7pBPGpZux/ldBlAOBPC0lJI3jZEL4jAHhu1DDPjG+qAbCW0SRToLJWQpuL/+v7AFanBsA55RyAZe/Id79s91oAYLa+ybK+I6NxsWz3iyUvdnCS19UdGP79a2UvZgIwy43wgJuVm2mU7AA6gA6gA+gAOoB2AAjxPUA+Rv/i6EIQQYpwNAAfrbXWDv7HZ/uUkNda6/WP9suXhZchhIMB+KiL/DBTUdsPCQSttQ5P0IQVAP5YAMLqSsIPvyX21oCg9bC0ROml9IcCiFrr6L3wIWr9dJo3ABDDwzifAjjBCYpq2r3Vdn8NkPKZg70EAK+rQc89XR0ZFgBWg8ZLkaT+pQUA8coHfBdA/fpgrbWxEKkBiBCttXYQ0ue3RfAplAgpax8e0vvjS+lDc7gRIWpth5AtPn1o9FIEfzCANd0eile0fgnAj14zFJOJWtvsQ0PlSH2a4fGlMIUbMf0JK6SUYgxFMT4Lml9ygjY9zpPxFwc+AQh10MhO007jCpUjjQlAcYJhHm3GIYtlKDoWQNBa60E8vGa9ECKMM1QACK21DUKIYBcAoi+/6Cf/KioANn+oT3Mshqi1HQY/hqL01tEA8mzbwYva42Wt8DY9/QhgGGdYxBmAYfq4OP8pAxCTseUMcHSCfgpF4XgAMmT9s8Xj1Wrs088FgKgeT9QA4oNTGQNs0YAHbzMCiFU4iMcDkCJEW3u8+nmyShcAs6AxVABC7VSGGcaZCSwc8CAXVKU/AYCUUvhhTIUrMx4fvwCYZXW+AuDrebWiAjF3grWpFQ3wswz0HABSShHsXN3XAMR6rsUqAJH0YYqvQ0UiMRCPAGZh6RwAyeOFJYCgdXwLgBy0tlLG2hkOi8IzzACEqwDIfvtlDVg3gWTSlV3XZiPCYEc/76+mAeVJZj4tzrQiVP5+cnOLZ45aD1O4lItqUPgSNMLkBCcfIPSJALIuDtUoV6KAqAa6CsDP1xYeymGvtZ6FwZp4OBiAj2FpArNIlAx6Mgs7jcbrJwBklSRWAHydQIgaQKUuwh4MwE4LYWKEH0vEFsMyNIZxar19CiCl13MvUpVJGar0JeGcUs9UFIUDAUSttY5DCMk7xWlscfaS1dqGMQEeQoglfVwBMJ/GYayJtB1C+p9jAmTtUIqPIf9BrW08cEVoeCzuRisulWuZ1OUaYsx8Hhx3rH3lMJUTi78TSzVYl5/xx2rgK6vC5cnsVBSWiD29NNg8phFZFGKwOkgpw3ItUdgq6fW22JOdQ02vxEVBIr1dKdC/Wwv4MAxD8LNfSa+JtZU9Mb2VX3xYyxJi7R/ChyEuPnR6bxiGlCf/tDLWt8Y6gA6gA+gAOoAOoAPoADqADqAD6AC6dOnSpUuXLl26dOnSpUuXLl26dOnSpUuXLl26dOnyfyMTAAB9K2SZH89pZAAAAABJRU5ErkJggg==)
      
      Solarvista Live is a Field Service Management platform to manage, plan, and mobilise your engineers.  The Matatika Solarvista Live
      import will extract Solarvista data into your Matatika data store, giving you instant insights into revenue, projects, work items, and engineer performance.


      ## Prerequisites

      Before importing data from Solarvista Live you will need to have performed the initial setup in Solarvista.
      
      [Solarvista Live Prerequisites](${docsBaseUrl}/datasources/tap-solarvista/prerequisites)


      ## Data source settings
      
      ### Account

      Solarvista API `account`

      To get your `account` id you will need to follow the steps that are linked in our [Prerequisites](${docsBaseUrl}/datasources/tap-solarvista/prerequisites) section.

      ### ClientId

      Solarvista API `clientId`
        
      To get your `clientId` you will need to follow the steps that are linked in our [Prerequisites](${docsBaseUrl}/datasources/tap-solarvista/prerequisites) section.
        
      ### Code
        
      Solarvista API `code`
        
      To get your `code` you will need to follow the steps that are linked in our [Prerequisites](${docsBaseUrl}/datasources/tap-solarvista/prerequisites) section.
        
      ### Datasources
        
      Leave this field blank to accept the default Solarvista datasources or customise the type of data to sync, we support:
      - `customer`
      - `site`
      - `equipment`
      - `work-item`
      - `work-item-history`
      - `activity`
      - `users`
      - `territory`
      - `project`
      - `appointment`
      - `skill`
        
        
      ### Start Date
        
      Providing a start date allows you to set how much historical data you wish to import into your workspace. 
        
      This date has to be in the ISO-8601 date format, see the example below.
        
      Format: `YYYY-MM-DDTHH:MM:SSZ`
      Example: `2020-10-01T13:12:11Z`

      
      ## Learn more
      
      Learn more about the Solarvista Live data source
      
      [Solavista Live Extractor Documentation](${docsBaseUrl}/datasources/tap-solarvista)
      
    namespace: tap_solarvista
    variants:
    - name: matatika
      docs: ${docsBaseUrl}/datasources/tap-solarvista/
      repo: https://github.com/Matatika/tap-solarvista
      pip_url: git+https://github.com/Matatika/tap-solarvista.git
      capabilities:
        - state
      settings:
        - name: datasources
          env_aliases:
            - TAP_SOLARVISTA_DATASOURCES
          label: Datasources
        - name: account
          env_aliases:
            - TAP_SOLARVISTA_ACCOUNT
          label: Account
        - name: clientId
          env_aliases:
            - TAP_SOLARVISTA_CLIENTID
          label: Client ID
        - name: code
          env_aliases:
            - TAP_SOLARVISTA_CODE
          label: Code
        - name: start_date
          env_aliases:
            - TAP_SOLARVISTA_START_DATE
          label: Start Date
          kind: date_iso8601
loaders:
transforms:
  - name: dbt-solarvista
    namespace: tap_solarvista
    variants:
    - name: matatika
      repo: https://github.com/Matatika/dbt-tap-solarvista
      pip_url: https://github.com/Matatika/dbt-tap-solarvista.git
      vars:
        schema: "{{ env_var('DBT_SOURCE_SCHEMA') }}"
models:
dashboards:
transformers:
files:
  - name: analyze-solarvista
    namespace: tap_solarvista
    update:
      analyze/datasets: true
    repo: https://github.com/Matatika/analyze-solarvista
    pip_url: git+https://github.com/Matatika/analyze-solarvista.git

```

## Checklist

- [x] Add a file in the appropriate folder (/taps or /targets). The name of the file should match the name of the tap. If there is already one, add a descriptor to the name such as `-search`.
- [x] Add a png logo image in `/assets/<taps or targets>`. The image name must match the YAML file name.
- [x] Tag `@tayloramurphy` or `@pnadolny13` to flag it for review. Or post to the hub channel on Meltano slack.

## Reviewer Checklist

- [ ] Validate file against JSON Schema. https://www.jsonschema.net/home is an option.
- [ ] Build website locally and validate everything works.
