### ISSUE TITLE
Generate metrics.yml for taps and targets

### ISSUE THREAD

**Issue by MeltyBot** [meltano/hub#39]
Migrated from GitLab: https://gitlab.com/meltano/hub/-/issues/40

Originally created by @tayloramurphy on 2021-05-10 23:44:33

---

Part of https://gitlab.com/meltano/hub/-/issues/11#note_571734864 will be generating a YAML file with a structure like:

```yaml
appsflyer:
  variants:
    - name: singer-io
      repo: https://github.com/singer-io/tap-appsflyer
      stars: 23
      open_issues: 23
      updated_at: timestamp
      last_commit: timestamp
      license: mit
adwords: #source_id
  variants:
    - name: singer-io
      repo: https://github.com/singer-io/tap-adwords
      stars: 23
      open_issues: 23
      updated_at: timestamp
      last_commit: timestamp
      license: MIT
```

Everything in the file will be machine-generated and will be interleaved with other data, which can then override if need be.
