### ISSUE TITLE
Singer executable ontology

### ISSUE THREAD

**Issue by MeltyBot** [meltano/hub#40]
Migrated from GitLab: https://gitlab.com/meltano/hub/-/issues/41

Originally created by @tayloramurphy on 2021-05-11 00:02:38

---

In discussions with AJ today we realized that the ontology of understanding the tap/target name was a bit confusing. We were conflating terms and getting confused between different variants / domains.

Initial Proposal:

Domain - This is the business/site/product from which data is being pulled/pushed. 
Name - This is the name of the tap/target sans any prefixes. 
Variant - One of N Singer-compatible taps/targets. This will typically map to a namespace for a given code hosting provider.
Unique ID - This is currently the full repository name as it's guaranteed to uniquely identify a tap / target across the internet. We may need a "better" unique ID.
Singer Name - typically `tap-<domain>`. This may not be entirely useful as `pipelinewise-tap-<domain>` is a common pattern and we've seen `singer-tap-<domain>`. And you can also take the `type` and join it with the domain name.

Facebook is a good test case. 

```yaml
domain: facebook
name: facebook
singer_name: tap-facebook
variant: 
  - name: <code_repo_namespace>
    repo: URL/tap-facebook
```

```yaml
domain: facebook
name: facebook-chats
singer_name: tap-facebook-chats
variant:
  - name: <code_repo_namespace>
    repo: URL/tap-facebook-chats
name: facebook-chats
```

This has a couple of really nice side effects:

1. The Domain allows us to group things very easily. For any domain that has multiple taps and targets, we can show them all on a single page for a given entity (BigQuery is the best example right now but this will grow as we have more SaaS Targets).
1. Using the repo as the unique ID will enable us to fully catch any forks or if the same provider most hosting platforms
  * For the short term we wouldn't use it as a join key though, we could simply use the name + variant combo
  * I'm not 100% sure how we should handle private taps yet. Perhaps the repo will still work.

Am I missing anything really big here? @DouweM @aaronsteers thoughts? I'm trying to mainly get our thoughts in order and get this properly encoded in the docs and JSON schema.
