### ISSUE TITLE
Generate scraped.yml for taps and targets

### ISSUE THREAD

**Issue by MeltyBot** [meltano/hub#41]
Migrated from GitLab: https://gitlab.com/meltano/hub/-/issues/42

Originally created by @tayloramurphy on 2021-05-11 00:06:38

---

Part of the output of https://gitlab.com/meltano/hub/-/issues/11#note_571734864 should be a single YAML file detailed the data we're able to readily pull from GitHub. 

A sample structure is:

```yaml
appsflyer:
  type: tap
  singer_name: tap-appsflyer #plugin_id
  variants:
    - name: singer-io
      repo: https://github.com/singer-io/tap-appsflyer
      pip_url: git+https://gitlab.com/meltano/tap-adwords.git
adwords:
  type: tap
  singer_name: tap-adwords #plugin_id
  variants:
    - name: meltano
      repo: https://gitlab.com/meltano/tap-adwords
      pip_url: git+https://gitlab.com/meltano/tap-adwords.git
```

For the data we've initially pulled in, we can simply strip `tap-`, `pipelinewise-tap-`, and `singer-tap-` from the name to generate the keys.
