### ISSUE TITLE
Enable Jekyll to read from multiple YAML files to generate full doc

### ISSUE THREAD

**Issue by MeltyBot** [meltano/hub#42]
Migrated from GitLab: https://gitlab.com/meltano/hub/-/issues/43

Originally created by @tayloramurphy on 2021-05-11 00:14:46

---

With [#40](https://gitlab.com/meltano/hub/-/issues/40) and [#42](https://gitlab.com/meltano/hub/-/issues/42) we're going to have multiple files representing different parts of the data structure for a given tap / target. 

* scraped.yml will be the result of [#11](https://gitlab.com/meltano/hub/-/issues/11) which will have a full list of taps/targets available from GitHub. The team will not be editing this and changes should come from dbt / whatever output script generates the file.
* Each tap / target will have their own file representing overrides or additions to the `scraped.yml` data
* Jekyll will need to be updated so that the generator which reads through all of the existing yaml files will pull in the scraped data.

I think having it "opt-in" only will work fine because new taps/targets can be discovered in the diff of `scraped.yml` and we'll do the minimal curation necessary to generate a full page. 

Minimal curation will be adding:

```yaml
      label: Appsflyer
      domain:
        type: api
        name: Appflyer
        url: 
      description: Advertising Platform
      maintenance_status: Unknown
```

and an image file.

We could also have a "hidden" flag too in case there are some that are worth scraping but add no value to the hub.
