### ISSUE TITLE
Add Evidence.dev utility to Hub, devops-friendly reporting tool

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/hub#518]
We should add Evidence.dev to the Hub as a reporting tool.

Evidence.dev is a BI/reporting tool that works very well in CI/CD environments.

Evidence uses Markdown as the reporting definition language, with jinja template support and specific extensions for rendering charts and visuals.

Related links:

- https://evidence.dev

A few example project using Evidence with Meltano:

- https://github.com/aaronsteers/aj-dataops-personal
- https://github.com/aaronsteers/evidence-analytics-monorepo/pull/2

**Comment by tayloramurphy** [comment]
FYI @pnadolny13 moved to a post-2.0 effort. Not essential for the launch.

**Comment by archiewood** [comment]
Also https://github.com/matsonj/nba-monte-carlo is an excellent example.
Deployed on mdsinabox.com

**Comment by visch** [comment]
gitlab ci

```
# The Docker image that will be used to build your app
pages:
  stage: run
  image: 
    name: $CI_REGISTRY_IMAGE:latest
    entrypoint: [""]
  variables:
    MELTANO_ENVIRONMENT: prod
    POSTGRES_DB: $TAP_POSTGRES_HOST
    POSTGRES_USER: $TAP_POSTGRES_HOST #Evidence.dev
    POSTGRES_PASSWORD: $TAP_POSTGRES_HOST #Evidence.dev
    POSTGRES_HOST_AUTH_METHOD: trust
    POSTGRES_HOST: $TAP_POSTGRES_HOST #Evidence.dev
    POSTGRES_DATABASE: $TAP_POSTGRES_HOST #Evidence.dev
    DATABASE: $TAP_POSTGRES_HOST #Evidence.dev
    POSTGRES_PORT: 5432 #Evidence.dev
# Functions that should be executed before the build script is run
  script:
    - cd /project/my-project
    - meltano run dashboard
    - apt update -y
    - apt install curl -y
    - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
    - apt install nodejs -y 
    - npm install
    - npm run build
    - cp -r build/ ${CI_PROJECT_DIR}/public
  artifacts:
    paths:
        # The folder that contains the files to be exposed at the Page URL
        - public
  rules:
      # This ensures that only pushes to the default branch will trigger
      # a pages deploy
  - if: ($CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web") && $mode == "dashboard"
  services:
  - postgres:12.2-alpine

```
