### ISSUE TITLE
Add "minimal meltano.yml setup" instructions to Hub. 

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/hub#524]
One thing we're losing from the markdown files currently is the recommended "minimal" configuration for discoverable extractors.

The following is an example from tap-adwords:

![Screen Shot 2022-06-02 at 5 06 15 PM](https://user-images.githubusercontent.com/5394188/171746284-6f7e0180-66b8-4b43-a971-a1606ffbde13.png)

#### Minimal configuration

A minimal configuration of `tap-adwords` in your [`meltano.yml` project file](https://docs.meltano.com/concepts/project#meltano-yml-project-file) will look like this:

```yml{5-7}
plugins:
  extractors:
  - name: tap-adwords
    variant: singer-io
    config:
      customer_ids: 1234567890,1234567891
      start_date: '2020-10-01T00:00:00Z'
```

Sensitive values are most appropriately stored in [the environment](https://docs.meltano.com/configuration.html#configuring-settings) or your project's [`.env` file](https://docs.meltano.com/concepts/project#env):
