### ISSUE TITLE
feat: handle more elaborate `pip_url` data for badge rendering

### ISSUE THREAD

**Issue by rwfeather** [meltano/hub#870]
Follow up to #869 

Current logic:
```js
hasPyPI() {
      // Exclude more elaborate ways of specifying `pip_url`
      // TODO: figure out what we should do when
      //   - multiple packages are listed space-delimited
      //   - packages have version specifiers (==, ~=)
      //   - packages specify optional dependencies in []
      return !(
        this.pip_url.includes("git+") ||
        this.pip_url.includes("//") ||
        this.pip_url.includes("=") ||
        this.pip_url.includes(" ") ||
        this.pip_url.includes("[")
      );
    },
```

When multiple packages are listed, I doubt we'll want to render a PyPI badge for each package (ex. dbt transformer is `pip_url: dbt-core~=1.1.0 dbt-postgres~=1.1.0 dbt-redshift~=1.1.0 dbt-snowflake~=1.1.0 dbt-bigquery~=1.1.0`)

The others could probably just have the extra stuff parsed out.

Would it be worth the effort to migrate this into a more data-structurey shape in the yaml files? I know that as-is they all slot right into a pip/requirements call, but having the mixed data types and space-delimited strings feels kinda code smell. Especially since they are surfaced in the Hub API as well.

**Comment by rwfeather** [comment]
Examples at a glance:

```yaml
pip_url: apache-airflow==2.1.2 --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.1.2/constraints-${MELTANO__PYTHON_VERSION}.txt

pip_url: dbt-core~=1.1.0 dbt-postgres~=1.1.0 dbt-redshift~=1.1.0 dbt-snowflake~=1.1.0 dbt-bigquery~=1.1.0

pip_url: git+https://github.com/meltanolabs/target-postgres.git

pip_url: https://gitlab.com/meltano/dbt-tap-stripe.git@config-version-2

pip_url: acryl-datahub[rest,dbt]
```
