### ISSUE TITLE
Redirect Hub JSON API traffic to AWS servers

### ISSUE THREAD

**Issue by aaronsteers** [meltano/hub#954]
After we have S3-backed hosting for the JSON endpoints, we'll need to make sure traffic gets from `https://hub.meltano.com/meltano/api/*` to the AWS servers.

I believe the [Netlify redirects syntax](https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file) can be used in `netlify.toml` - but there may be other ways to implement this as well. There's an optional `force` flag to ignore other content that is Gridsome/Netlify managed.

Maybe something like this?: 

```toml
[[redirects]]
  from = "/meltano/api/*"
  to = "https://something.amazon.com/our/prod/endpoint/prefix/:splat"
  force = true
```

cc @pandemicsyn, @rwfeather, @edgarrmondragon
